name: nuevo_proyecto
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+33

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.9
  google_fonts: ^4.0.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.2
  pie_chart: ^5.0.1
  image_picker: ^0.8.4+4
  lottie: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  google_sign_in: ^6.1.2
  collection: ^1.16.0
  permission_handler: ^11.4.0
  timezone: ^0.10.0
  android_intent_plus: ^5.3.0
  firebase_messaging: ^15.2.4
  google_mobile_ads: 6.0.0
  in_app_purchase: 3.2.1
  video_player: 2.9.5
  user_messaging_platform: ^1.3.0


dependency_overrides:
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "icons/fit_league.png"
  adaptive_icon_background: "#002B5B"
  adaptive_icon_foreground: "icons/fit_league.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - icons/diet.png
    - icons/progreso.png
    - icons/exercise.png
    - assets/cadera_mujeres.jpg
    - assets/cintura_mujeres.jpg
    - assets/cuello_hombres.jpg
    - assets/cintura_hombres.jpg
    - assets/spain_flag.png
    - assets/uk_flag.png
    - assets/fit_league1.png
    - assets/animations/food-vlogger.json
    - assets/animations/select-food.json
